import { useAnalysisStore } from '../../store/analysisStore';
import { Download, RotateCcw, Trophy, Target, Timer, TrendingUp, Gauge } from 'lucide-react';

export function ResultsDisplay() {
  const { result, reset, videoFile } = useAnalysisStore();

  if (!result) return null;

  const handleExport = () => {
    if (!result || !videoFile) return;

    const exportText = `Hammer Throw Analysis
====================

Video: ${videoFile.name}
Date: ${new Date().toLocaleDateString()}

RESULTS
-------
Distance: ${result.distance.toFixed(1)} meters
Flight Time: ${result.flightTime.toFixed(2)} seconds
Release Velocity: ${result.releaseVelocity.toFixed(1)} m/s
Release Angle: ${result.releaseAngle.toFixed(1)} degrees
Release Height: ${result.releaseHeight.toFixed(2)} m
Landing Velocity: ${result.landingVelocity.toFixed(1)} m/s

IMPLEMENT
---------
Type: ${result.implement.name}
Mass: ${result.implement.massKg} kg
Diameter: ${result.implement.diameterMm} mm

CALIBRATION
-----------
Camera Angle: ${result.cameraAngle.type}
Confidence: ${(result.confidence * 100).toFixed(0)}%

---
Generated by Hammer Throw Analyzer`;

    const blob = new Blob([exportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `hammer-throw-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getDistanceLabel = (distance: number) => {
    if (distance >= 75) return { label: 'Elite!', color: 'text-purple-600', icon: Trophy };
    if (distance >= 60) return { label: 'Excellent', color: 'text-blue-600', icon: Trophy };
    if (distance >= 45) return { label: 'Good', color: 'text-green-600', icon: Target };
    return { label: 'Training', color: 'text-orange-600', icon: Target };
  };

  const distanceInfo = getDistanceLabel(result.distance);
  const DistanceIcon = distanceInfo.icon;

  return (
    <div className="w-full max-w-4xl mx-auto mt-6">
      <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 p-8 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-blue-100 text-sm font-medium uppercase tracking-wide">
                Throw Distance
              </p>
              <div className="flex items-baseline space-x-2 mt-1">
                <span className="text-6xl font-bold">
                  {result.distance.toFixed(1)}
                </span>
                <span className="text-2xl text-blue-200">m</span>
              </div>
            </div>
            <div className="text-right">
              <div className={`flex items-center space-x-2 ${distanceInfo.color}`}>
                <DistanceIcon className="w-6 h-6" />
                <span className="text-2xl font-bold">{distanceInfo.label}</span>
              </div>
              <p className="text-blue-200 text-sm mt-1">
                {result.implement.name} · {result.implement.massKg}kg
              </p>
            </div>
          </div>
        </div>

        {/* Metrics Grid */}
        <div className="p-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <MetricCard
              icon={Gauge}
              label="Release Velocity"
              value={`${result.releaseVelocity.toFixed(1)} m/s`}
            />
            <MetricCard
              icon={TrendingUp}
              label="Release Angle"
              value={`${result.releaseAngle.toFixed(1)}°`}
            />
            <MetricCard
              icon={Timer}
              label="Flight Time"
              value={`${result.flightTime.toFixed(2)} s`}
            />
            <MetricCard
              icon={Target}
              label="Confidence"
              value={`${(result.confidence * 100).toFixed(0)}%`}
            />
          </div>

          {/* Additional Details */}
          <div className="mt-8 pt-8 border-t border-gray-200">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">
              Additional Information
            </h3>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-500">Release Height</span>
                <span className="font-medium">{result.releaseHeight.toFixed(2)} m</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-500">Landing Velocity</span>
                <span className="font-medium">{result.landingVelocity.toFixed(1)} m/s</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-500">Camera Angle</span>
                <span className="font-medium capitalize">{result.cameraAngle.type}</span>
              </div>
              <div className="flex justify-between py-2 border-b border-gray-100">
                <span className="text-gray-500">Hammer Diameter</span>
                <span className="font-medium">{result.implement.diameterMm} mm</span>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="mt-8 flex justify-center space-x-4">
            <button
              onClick={handleExport}
              className="flex items-center space-x-2 px-6 py-3 bg-gray-900 hover:bg-gray-800 text-white rounded-xl font-medium transition-colors"
            >
              <Download className="w-5 h-5" />
              <span>Export Results</span>
            </button>
            
            <button
              onClick={reset}
              className="flex items-center space-x-2 px-6 py-3 border-2 border-gray-300 hover:border-gray-400 text-gray-700 rounded-xl font-medium transition-colors"
            >
              <RotateCcw className="w-5 h-5" />
              <span>Analyze Another</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

interface MetricCardProps {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
}

function MetricCard({ icon: Icon, label, value }: MetricCardProps) {
  return (
    <div className="bg-gray-50 rounded-xl p-4">
      <div className="flex items-center space-x-2 text-gray-500 mb-2">
        <Icon className="w-4 h-4" />
        <span className="text-xs font-medium uppercase tracking-wide">{label}</span>
      </div>
      <p className="text-xl font-bold text-gray-900">{value}</p>
    </div>
  );
}